Name:           ros-melodic-people-tracking-filter
Version:        1.2.0
Release:        1%{?dist}
Summary:        ROS people_tracking_filter package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/people_tracking_filter
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-bfl
Requires:       ros-melodic-geometry-msgs
Requires:       ros-melodic-message-filters
Requires:       ros-melodic-people-msgs
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-sensor-msgs
Requires:       ros-melodic-std-msgs
Requires:       ros-melodic-tf
BuildRequires:  ros-melodic-bfl
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-geometry-msgs
BuildRequires:  ros-melodic-message-filters
BuildRequires:  ros-melodic-people-msgs
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-sensor-msgs
BuildRequires:  ros-melodic-std-msgs
BuildRequires:  ros-melodic-tf

%description
A collection of filtering tools for tracking people's locations

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Mon Aug 19 2019 David V. Lu!! <davidvlu@gmail.com> - 1.2.0-1
- Autogenerated by Bloom

* Thu Aug 30 2018 David V. Lu!! <davidvlu@gmail.com> - 1.1.2-0
- Autogenerated by Bloom

* Wed Aug 29 2018 David V. Lu!! <davidvlu@gmail.com> - 1.1.1-0
- Autogenerated by Bloom

